if: tag IS blank

git:
  depth: 3

branches:
  only:
  - master
  - /^v-.*$/

language: node_js
node_js:
  - "10"
  - "8"
  - "6"

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set loglevel warn
  - npm install --global npm@latest

script:
  - npm run ci
